# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ShoppingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Gallery'
  pod 'InstantSearchClient'
  pod 'EmptyDataSet-Swift'
  pod 'NVActivityIndicatorView/AppExtension'
  pod 'JGProgressHUD'
  pod 'PayPal-iOS-SDK'
  
end
